package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Badminton;
import org.hzy.bshop.entity.BadmintonExample;

public interface BadmintonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    long countByExample(BadmintonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByExample(BadmintonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insert(Badminton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insertSelective(Badminton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    List<Badminton> selectByExample(BadmintonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    Badminton selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Badminton record, @Param("example") BadmintonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Badminton record, @Param("example") BadmintonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Badminton record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_badminton
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKey(Badminton record);
}