package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Handle;
import org.hzy.bshop.entity.HandleExample;

public interface HandleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    long countByExample(HandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByExample(HandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insert(Handle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insertSelective(Handle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    List<Handle> selectByExample(HandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    Handle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Handle record, @Param("example") HandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Handle record, @Param("example") HandleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Handle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handle
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKey(Handle record);
}