package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Racket;
import org.hzy.bshop.entity.RacketExample;

public interface RacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    long countByExample(RacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int deleteByExample(RacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int insert(Racket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int insertSelective(Racket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    List<Racket> selectByExample(RacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    Racket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Racket record, @Param("example") RacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Racket record, @Param("example") RacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Racket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_racket
     *
     * @mbg.generated Tue Mar 28 17:09:08 GMT+08:00 2023
     */
    int updateByPrimaryKey(Racket record);
}