package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Series;
import org.hzy.bshop.entity.SeriesExample;

public interface SeriesMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    long countByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insert(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insertSelective(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    List<Series> selectByExample(SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    Series selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Series record, @Param("example") SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Series record, @Param("example") SeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_series
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKey(Series record);

    List<Series> selectAll();

    List<Series> selectByBrandId(int id);
}