package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Speed;
import org.hzy.bshop.entity.SpeedExample;

public interface SpeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    long countByExample(SpeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByExample(SpeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insert(Speed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insertSelective(Speed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    List<Speed> selectByExample(SpeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    Speed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Speed record, @Param("example") SpeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Speed record, @Param("example") SpeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Speed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_speed
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKey(Speed record);
}