package org.hzy.bshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hzy.bshop.entity.Weight;
import org.hzy.bshop.entity.WeightExample;

public interface WeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    long countByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insert(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int insertSelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    List<Weight> selectByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    Weight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByExample(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weight
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    int updateByPrimaryKey(Weight record);
}