package org.hzy.bshop.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.nick_name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.account
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.password
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.nick_name
     *
     * @return the value of t_admin.nick_name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.nick_name
     *
     * @param nickName the value for t_admin.nick_name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.account
     *
     * @return the value of t_admin.account
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.account
     *
     * @param account the value for t_admin.account
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.password
     *
     * @return the value of t_admin.password
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.password
     *
     * @param password the value for t_admin.password
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}