package org.hzy.bshop.entity;

import lombok.Data;

@Data
public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.tm_path
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String tmPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.description
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_brand.is_deleted
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.id
     *
     * @return the value of t_brand.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.id
     *
     * @param id the value for t_brand.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.name
     *
     * @return the value of t_brand.name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.name
     *
     * @param name the value for t_brand.name
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.tm_path
     *
     * @return the value of t_brand.tm_path
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getTmPath() {
        return tmPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.tm_path
     *
     * @param tmPath the value for t_brand.tm_path
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setTmPath(String tmPath) {
        this.tmPath = tmPath == null ? null : tmPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.description
     *
     * @return the value of t_brand.description
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public String getDescription() {
        return description;
    }
    public String getShortDesc(){
        if(description.length()>40){
            return description.substring(0,40)+"...";
        }else{
            return description;
        }
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.description
     *
     * @param description the value for t_brand.description
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_brand.is_deleted
     *
     * @return the value of t_brand.is_deleted
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_brand.is_deleted
     *
     * @param isDeleted the value for t_brand.is_deleted
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}