package org.hzy.bshop.entity;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.user_id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.total_price
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    private Double totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.id
     *
     * @return the value of t_cart.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.id
     *
     * @param id the value for t_cart.id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.user_id
     *
     * @return the value of t_cart.user_id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.user_id
     *
     * @param userId the value for t_cart.user_id
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.total_price
     *
     * @return the value of t_cart.total_price
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.total_price
     *
     * @param totalPrice the value for t_cart.total_price
     *
     * @mbg.generated Sat Mar 25 10:12:48 GMT+08:00 2023
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
}